FROM python:3.13.14-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir uv==0.12.5
RUN uv sync --frozen --no-install-project --no-dev

COPY src/agents/ ./agents/
COPY src/agent_foundation/ ./agent_foundation/
COPY src/control_plane/ ./control_plane/
COPY src/core/ ./core/
COPY src/memory/ ./memory/
COPY src/model_gateway/ ./model_gateway/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/run_service.py .

CMD ["python", "run_service.py"]
